import { Octokit } from "octokit";
import type { GeneratedFile } from "@/types";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const owner = process.env.GITHUB_ORG!;

// ─────────────────────────────────────────────
//  Create a new private repo and push generated files
// ─────────────────────────────────────────────

export async function createRepoAndPushFiles(
  repoName: string,
  description: string,
  files: GeneratedFile[]
): Promise<string> {
  // 1. Create the repo
  const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
    name: repoName,
    description,
    private: true,
    auto_init: false,
  });

  const repoUrl = repo.html_url;

  // 2. Create an initial commit with all files
  // Get the default branch ref first (might not exist yet on empty repos)
  // We'll create a tree directly

  // Encode file contents
  const treeItems = files.map((f) => ({
    path: f.path,
    mode: "100644" as const,
    type: "blob" as const,
    content: f.content,
  }));

  // Create tree
  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo: repoName,
    tree: treeItems,
  });

  // Create commit
  const { data: commit } = await octokit.rest.git.createCommit({
    owner,
    repo: repoName,
    message: "🚀 Initial app generated by IdeaLaunch",
    tree: tree.sha,
    parents: [],
  });

  // Create main branch pointing to the commit
  await octokit.rest.git.createRef({
    owner,
    repo: repoName,
    ref: "refs/heads/main",
    sha: commit.sha,
  });

  return repoUrl;
}

// ─────────────────────────────────────────────
//  Grant repo access to a user (optional feature)
// ─────────────────────────────────────────────

export async function grantRepoAccess(
  repoName: string,
  username: string
): Promise<void> {
  await octokit.rest.repos.addCollaborator({
    owner,
    repo: repoName,
    username,
    permission: "push",
  });
}

// ─────────────────────────────────────────────
//  Sanitize a name to be a valid GitHub repo name
// ─────────────────────────────────────────────

export function sanitizeRepoName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 100);
}
