"use client";

import { useState, useEffect } from "react";
import {
  Check,
  X,
  Loader2,
  Rocket,
  Download,
  ChevronRight,
  Users,
  Lightbulb,
  Layout,
  MessageSquare,
  AlertCircle,
} from "lucide-react";
import type { Requirement, AppBlueprint } from "@/types";

const CATEGORY_LABELS: Record<string, string> = {
  feature: "Features",
  design: "Design",
  data: "Data",
  auth: "Auth",
  integration: "Integrations",
};

const CATEGORY_COLORS: Record<string, { text: string; bg: string; border: string }> = {
  feature: { text: "text-terra", bg: "bg-terra/8", border: "border-terra/20" },
  design: { text: "text-emerald-600", bg: "bg-emerald-50", border: "border-emerald-200" },
  data: { text: "text-blue-600", bg: "bg-blue-50", border: "border-blue-200" },
  auth: { text: "text-violet-600", bg: "bg-violet-50", border: "border-violet-200" },
  integration: { text: "text-pink-600", bg: "bg-pink-50", border: "border-pink-200" },
};

interface RequirementsReviewProps {
  projectId: string;
  blueprint: AppBlueprint;
  onApproved: () => void;
  onEdit: () => void;
}

function downloadBlueprint(blueprint: AppBlueprint) {
  const lines: string[] = [
    `APP BLUEPRINT — ${blueprint.appName.toUpperCase()}`,
    "=".repeat(50),
    "",
    "PURPOSE",
    "-".repeat(30),
    blueprint.purpose,
    "",
    "TARGET USER",
    "-".repeat(30),
    blueprint.targetUser,
    "",
    "TONE & VOICE",
    "-".repeat(30),
    blueprint.tone,
    "",
    "CORE FEATURES",
    "-".repeat(30),
    ...blueprint.coreFeatures.map((f, i) => `${i + 1}. ${f}`),
    "",
    "PAGES",
    "-".repeat(30),
    ...blueprint.pages.map((p, i) => `${i + 1}. ${p}`),
    "",
    "DATA MODELS",
    "-".repeat(30),
    ...blueprint.dataModels.map((d, i) => `${i + 1}. ${d}`),
    "",
    "CONSTRAINTS",
    "-".repeat(30),
    ...blueprint.constraints.map((c, i) => `${i + 1}. ${c}`),
    "",
    "-".repeat(50),
    `Generated by IdeaLaunch · ${new Date().toLocaleDateString()}`,
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${blueprint.appName.replace(/\s+/g, "-").toLowerCase()}-blueprint.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function RequirementsReview({
  projectId,
  blueprint,
  onApproved,
  onEdit,
}: RequirementsReviewProps) {
  const [requirements, setRequirements] = useState<Requirement[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    async function loadRequirements() {
      const res = await fetch("/api/requirements", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId }),
      });
      const data = await res.json();
      setRequirements(data.requirements ?? []);
      setLoading(false);
    }
    loadRequirements();
  }, [projectId]);

  function toggleRequirement(id: string) {
    setRequirements((prev) =>
      prev.map((r) => (r.id === id ? { ...r, approved: !r.approved } : r))
    );
  }

  async function handleApprove() {
    setSaving(true);
    await fetch("/api/requirements", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ projectId, requirements }),
    });
    setSaving(false);
    onApproved();
  }

  const approvedCount = requirements.filter((r) => r.approved).length;

  const grouped = requirements.reduce<Record<string, Requirement[]>>(
    (acc, req) => {
      if (!acc[req.category]) acc[req.category] = [];
      acc[req.category].push(req);
      return acc;
    },
    {}
  );

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-3">
        <Loader2 size={24} className="text-terra animate-spin" />
        <p className="text-ink-lighter text-sm">Generating your build plan…</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">

      {/* ── Blueprint summary card ─────────────────────────────── */}
      <div className="rounded-2xl border border-border bg-white shadow-sm overflow-hidden">
        {/* Card header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-border bg-cream">
          <div>
            <h2 className="font-bold font-heading text-navy text-lg">
              {blueprint.appName}
            </h2>
            <p className="text-xs text-ink-lighter mt-0.5">App Blueprint</p>
          </div>
          <button
            onClick={() => downloadBlueprint(blueprint)}
            className="flex items-center gap-1.5 text-xs text-ink-lighter hover:text-navy border border-border rounded-lg px-3 py-1.5 transition-colors bg-white hover:bg-cream"
          >
            <Download size={13} />
            Download
          </button>
        </div>

        {/* Blueprint fields */}
        <div className="divide-y divide-border">
          {/* Purpose */}
          <div className="flex gap-3 px-5 py-4">
            <div className="w-7 h-7 rounded-lg bg-terra/10 flex items-center justify-center shrink-0 mt-0.5">
              <Lightbulb size={14} className="text-terra" />
            </div>
            <div>
              <p className="text-xs font-semibold text-ink-lighter uppercase tracking-wide mb-1">What it does</p>
              <p className="text-sm text-ink leading-relaxed">{blueprint.purpose}</p>
            </div>
          </div>

          {/* Target user */}
          <div className="flex gap-3 px-5 py-4">
            <div className="w-7 h-7 rounded-lg bg-navy/8 flex items-center justify-center shrink-0 mt-0.5">
              <Users size={14} className="text-navy" />
            </div>
            <div>
              <p className="text-xs font-semibold text-ink-lighter uppercase tracking-wide mb-1">Built for</p>
              <p className="text-sm text-ink leading-relaxed">{blueprint.targetUser}</p>
            </div>
          </div>

          {/* Tone */}
          <div className="flex gap-3 px-5 py-4">
            <div className="w-7 h-7 rounded-lg bg-gold/10 flex items-center justify-center shrink-0 mt-0.5">
              <MessageSquare size={14} className="text-gold-dark" />
            </div>
            <div>
              <p className="text-xs font-semibold text-ink-lighter uppercase tracking-wide mb-1">Tone &amp; voice</p>
              <p className="text-sm text-ink leading-relaxed">{blueprint.tone}</p>
            </div>
          </div>

          {/* Core features */}
          <div className="flex gap-3 px-5 py-4">
            <div className="w-7 h-7 rounded-lg bg-terra/10 flex items-center justify-center shrink-0 mt-0.5">
              <Layout size={14} className="text-terra" />
            </div>
            <div className="flex-1">
              <p className="text-xs font-semibold text-ink-lighter uppercase tracking-wide mb-2">Core features</p>
              <ul className="space-y-1.5">
                {blueprint.coreFeatures.map((f, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-ink">
                    <span className="w-4 h-4 rounded-full bg-terra/15 text-terra flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
                      {i + 1}
                    </span>
                    {f}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Pages */}
          <div className="px-5 py-4">
            <p className="text-xs font-semibold text-ink-lighter uppercase tracking-wide mb-2">Pages</p>
            <div className="flex flex-wrap gap-2">
              {blueprint.pages.map((p) => (
                <span
                  key={p}
                  className="inline-flex items-center px-2.5 py-1 rounded-lg bg-cream-dark border border-border text-xs font-medium text-ink"
                >
                  {p}
                </span>
              ))}
            </div>
          </div>

          {/* Constraints */}
          {blueprint.constraints.length > 0 && (
            <div className="flex gap-3 px-5 py-4">
              <div className="w-7 h-7 rounded-lg bg-amber-50 flex items-center justify-center shrink-0 mt-0.5">
                <AlertCircle size={14} className="text-amber-600" />
              </div>
              <div className="flex-1">
                <p className="text-xs font-semibold text-ink-lighter uppercase tracking-wide mb-2">Constraints &amp; guardrails</p>
                <ul className="space-y-1">
                  {blueprint.constraints.map((c, i) => (
                    <li key={i} className="text-sm text-ink-light leading-relaxed">
                      · {c}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── Requirements checklist ─────────────────────────────── */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-semibold font-heading text-navy">Build checklist</h3>
          <span className="text-xs text-ink-lighter">
            Uncheck anything you don&apos;t want
          </span>
        </div>

        <div className="space-y-5">
          {Object.entries(grouped).map(([category, reqs]) => {
            const colors = CATEGORY_COLORS[category] ?? {
              text: "text-ink-lighter",
              bg: "bg-cream",
              border: "border-border",
            };
            return (
              <div key={category}>
                <p className={`text-xs font-semibold uppercase tracking-wider mb-2 ${colors.text}`}>
                  {CATEGORY_LABELS[category] ?? category}
                </p>
                <div className="space-y-2">
                  {reqs.map((req) => (
                    <button
                      key={req.id}
                      onClick={() => toggleRequirement(req.id)}
                      className={`w-full flex items-start gap-3 p-4 rounded-xl border text-left transition-all ${
                        req.approved
                          ? "bg-white border-border hover:border-terra/30"
                          : "bg-cream-dark border-border opacity-50"
                      }`}
                    >
                      <div
                        className={`shrink-0 w-5 h-5 rounded-md border flex items-center justify-center mt-0.5 transition-colors ${
                          req.approved
                            ? "bg-terra border-terra"
                            : "border-border bg-white"
                        }`}
                      >
                        {req.approved ? (
                          <Check size={11} className="text-white" />
                        ) : (
                          <X size={11} className="text-ink-lighter" />
                        )}
                      </div>
                      <div>
                        <p className="text-sm font-medium text-navy">{req.title}</p>
                        <p className="text-xs text-ink-lighter mt-0.5">{req.description}</p>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* ── Action buttons ─────────────────────────────────────── */}
      <div className="space-y-3 pt-2">
        <button
          onClick={handleApprove}
          disabled={approvedCount === 0 || saving}
          className="w-full flex items-center justify-center gap-2 bg-terra hover:bg-terra/90 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold py-4 rounded-xl transition-colors text-base"
        >
          {saving ? (
            <Loader2 size={18} className="animate-spin" />
          ) : (
            <>
              <Rocket size={18} />
              Approve &amp; build my app
              <ChevronRight size={18} />
            </>
          )}
        </button>

        <button
          onClick={onEdit}
          className="w-full flex items-center justify-center gap-2 text-ink-light hover:text-navy border border-border hover:border-navy/30 bg-white font-medium py-3 rounded-xl transition-colors text-sm"
        >
          ← Go back and edit my idea
        </button>
      </div>
    </div>
  );
}
